use crate::blockchain::types::AccountId;
use crate::crypto::AccountKeypair;
use crate::tee::detector::{detect_host_tee, HostTeeStatus};
use crate::tee::types::{AttestationQuote, EnclaveMeasurement, TeeSecurityFlags, TeeType};
use anyhow::Result;
use sha2::{Digest, Sha256};
use std::collections::HashSet;
use std::time::{SystemTime, UNIX_EPOCH};

/// Hardware TEE Sandbox Enclave generating verifiable remote attestation quotes.
#[derive(Clone)]
pub struct HardwareTeeEnclave {
    pub tee_type: TeeType,
    pub enclave_id: String,
    pub measurement: EnclaveMeasurement,
    pub security_flags: TeeSecurityFlags,
    platform_keypair: AccountKeypair,
}

impl HardwareTeeEnclave {
    /// Initialize a new Hardware TEE Enclave instance with default production security flags.
    pub fn new(tee_type: TeeType, enclave_name: impl Into<String>) -> Self {
        Self::new_with_flags(tee_type, enclave_name, TeeSecurityFlags::genuine_production())
    }

    /// Initialize a new Hardware TEE Enclave with explicit security and simulation flags.
    pub fn new_with_flags(
        tee_type: TeeType,
        enclave_name: impl Into<String>,
        security_flags: TeeSecurityFlags,
    ) -> Self {
        let name = enclave_name.into();

        // Deterministic measurement based on enclave code hash / name
        let mut mrenclave_hasher = Sha256::new();
        match tee_type {
            TeeType::IntelTdx => mrenclave_hasher.update(b"depeft_intel_tdx_mrtd_evaluator_v1.0.0"),
            _ => mrenclave_hasher.update(b"depeft_tee_validator_evaluator_v1.0.0"),
        }
        mrenclave_hasher.update(name.as_bytes());
        let mrenclave: [u8; 32] = mrenclave_hasher.finalize().into();

        let mut mrsigner_hasher = Sha256::new();
        match tee_type {
            TeeType::IntelTdx => mrsigner_hasher.update(b"depeft_intel_tdx_rtmr0_authority_root_key"),
            _ => mrsigner_hasher.update(b"depeft_foundation_enclave_authority_root_key"),
        }
        let mrsigner: [u8; 32] = mrsigner_hasher.finalize().into();

        let measurement = EnclaveMeasurement {
            mrenclave,
            mrsigner,
            isv_prod_id: 1,
            isv_svn: 1,
        };

        let platform_keypair = AccountKeypair::generate();

        Self {
            tee_type,
            enclave_id: name,
            measurement,
            security_flags,
            platform_keypair,
        }
    }

    /// Construct a local simulator enclave (testnet / development only).
    pub fn official(tee_type: TeeType) -> Self {
        Self::new_with_flags(
            tee_type,
            "official-validator-enclave",
            TeeSecurityFlags::simulation(),
        )
    }

    /// Automatically probe host OS for physical TEE devices;
    /// if absent, safely fall back to simulation mode with appropriate flags.
    pub fn detect_or_simulate(tee_type: TeeType) -> Self {
        match detect_host_tee() {
            HostTeeStatus::HardwareAvailable {
                tee_type: detected,
                device_path,
            } if detected == tee_type => {
                println!(
                    "[*] Genuine Hardware TEE Detected: {} via {}",
                    detected, device_path
                );
                Self::new_with_flags(
                    tee_type,
                    "genuine-hardware-enclave",
                    TeeSecurityFlags::genuine_production(),
                )
            }
            HostTeeStatus::HardwareAvailable {
                tee_type: detected,
                device_path,
            } => {
                println!(
                    "[!] Warning: Hardware device found for {} ({}), but requested {}; using simulator",
                    detected, device_path, tee_type
                );
                Self::official(tee_type)
            }
            HostTeeStatus::SimulationOnly { reason } => {
                println!(
                    "[!] Note: No hardware TEE detected ({}); running in software simulation mode",
                    reason
                );
                Self::official(tee_type)
            }
        }
    }

    /// Returns the set of canonical measurements generated by official software simulation enclaves.
    /// Used by OnChainTeeVerifier to detect spoofed simulation quotes pretending to be real hardware.
    pub fn known_simulator_measurements() -> HashSet<[u8; 32]> {
        let mut set = HashSet::new();
        for t in &[
            TeeType::IntelSgxDcap,
            TeeType::IntelTdx,
            TeeType::AmdSevSnp,
            TeeType::AwsNitroEnclave,
        ] {
            let enc = Self::official(*t);
            set.insert(enc.measurement.mrenclave);
        }
        set
    }

    /// Get platform public key bytes.
    pub fn platform_public_key(&self) -> [u8; 32] {
        self.platform_keypair.public_key_bytes()
    }

    /// Generate an Attestation Quote cryptographically bound to the evaluation ranking.
    pub fn generate_quote(
        &self,
        task_id: u64,
        round: usize,
        ranking: &[AccountId],
    ) -> Result<AttestationQuote> {
        let report_data = AttestationQuote::compute_report_data(task_id, round, ranking);
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        // Canonical payload signed by quoting key:
        // (tee_type || mrenclave || mrsigner || report_data || timestamp || is_simulation || debug_mode || hardware_level)
        let quote_payload = AttestationQuote::construct_quote_payload(
            self.tee_type,
            &self.measurement,
            &report_data,
            timestamp,
            &self.security_flags,
        );

        let quote_signature = self.platform_keypair.sign_message(&quote_payload);

        Ok(AttestationQuote {
            tee_type: self.tee_type,
            measurement: self.measurement.clone(),
            report_data,
            platform_public_key: self.platform_keypair.public_key_bytes(),
            quote_signature,
            timestamp,
            security_flags: self.security_flags,
        })
    }
}
