use crate::candle_peft::tokenizer::SimpleByteTokenizer;
use crate::candle_peft::transformer::CandleTransformerLM;
use anyhow::Result;
use candle_core::safetensors::save;
use candle_nn::{AdamW, Optimizer, ParamsAdamW, SGD};
use rand::RngCore;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// Optimizer type supported by Candle PEFT Miner.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PeftOptimizerType {
    AdamW,
    Adam,
    SGD,
}

impl Default for PeftOptimizerType {
    fn default() -> Self {
        Self::AdamW
    }
}

impl std::fmt::Display for PeftOptimizerType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::AdamW => write!(f, "AdamW"),
            Self::Adam => write!(f, "Adam"),
            Self::SGD => write!(f, "SGD"),
        }
    }
}

impl std::str::FromStr for PeftOptimizerType {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self> {
        match s.to_lowercase().as_str() {
            "adamw" | "adam-w" => Ok(Self::AdamW),
            "adam" => Ok(Self::Adam),
            "sgd" => Ok(Self::SGD),
            other => anyhow::bail!("Unknown optimizer: '{}'. Supported: adamw, adam, sgd", other),
        }
    }
}

/// Dynamic Candle Optimizer wrapper enum (since candle_nn::Optimizer is not dyn compatible).
pub enum CandleOptimizer {
    AdamW(AdamW),
    SGD(SGD),
}

impl CandleOptimizer {
    pub fn step(&mut self, grads: &candle_core::backprop::GradStore) -> Result<()> {
        match self {
            Self::AdamW(opt) => opt.step(grads)?,
            Self::SGD(opt) => opt.step(grads)?,
        }
        Ok(())
    }
}

/// Training hyper-parameters for Candle Miner.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CandleMinerHyperparams {
    pub learning_rate: f64,
    pub steps: usize,
    pub batch_size: usize,
    pub optimizer_type: PeftOptimizerType,
    pub weight_decay: f64,
    pub beta1: f64,
    pub beta2: f64,
    pub eps: f64,
    pub hardware_info: String,
}

impl Default for CandleMinerHyperparams {
    fn default() -> Self {
        Self {
            learning_rate: 0.001,
            steps: 20,
            batch_size: 4,
            optimizer_type: PeftOptimizerType::AdamW,
            weight_decay: 0.01,
            beta1: 0.9,
            beta2: 0.999,
            eps: 1e-8,
            hardware_info: "NVIDIA CUDA / Candle Auto-Diff".to_string(),
        }
    }
}

/// Training artifact generated by a Candle miner node.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CandleTrainingArtifact {
    pub train_loss: f32,
    pub final_loss: f32,
    pub safetensors_bytes: Vec<u8>,
    pub commit_hash: [u8; 32],
    pub salt: [u8; 32],
    pub adapter_hash: [u8; 32],
    pub hardware_info: String,
}

/// Miner trainer executing real LoRA backpropagation and SafeTensors export on Candle models.
pub struct CandleMinerTrainer;

impl CandleMinerTrainer {
    /// Fine-tune LoRA parameters on a set of text training samples using Candle autograd.
    pub fn train(
        model: &mut CandleTransformerLM,
        text_samples: &[String],
        hyperparams: &CandleMinerHyperparams,
    ) -> Result<CandleTrainingArtifact> {
        let tokenizer = SimpleByteTokenizer::new();
        let encoded_samples: Vec<Vec<u32>> = text_samples
            .iter()
            .map(|text| tokenizer.encode(text))
            .filter(|v| v.len() >= 2)
            .collect();

        if encoded_samples.is_empty() {
            anyhow::bail!("No valid training samples provided");
        }

        let vars = model.get_trainable_vars();

        // Instantiate chosen optimizer (AdamW, Adam, or SGD)
        let mut optimizer = match hyperparams.optimizer_type {
            PeftOptimizerType::AdamW => {
                let params = ParamsAdamW {
                    lr: hyperparams.learning_rate,
                    beta1: hyperparams.beta1,
                    beta2: hyperparams.beta2,
                    eps: hyperparams.eps,
                    weight_decay: hyperparams.weight_decay,
                };
                CandleOptimizer::AdamW(AdamW::new(vars, params)?)
            }
            PeftOptimizerType::Adam => {
                // Adam is AdamW without weight decay (L2 decoupled penalty = 0.0)
                let params = ParamsAdamW {
                    lr: hyperparams.learning_rate,
                    beta1: hyperparams.beta1,
                    beta2: hyperparams.beta2,
                    eps: hyperparams.eps,
                    weight_decay: 0.0,
                };
                CandleOptimizer::AdamW(AdamW::new(vars, params)?)
            }
            PeftOptimizerType::SGD => CandleOptimizer::SGD(SGD::new(vars, hyperparams.learning_rate)?),
        };

        let mut initial_loss_val = 0.0f32;
        let mut final_loss_val = 0.0f32;

        for step in 0..hyperparams.steps {
            // Select batch
            let start_idx = (step * hyperparams.batch_size) % encoded_samples.len();
            let end_idx = (start_idx + hyperparams.batch_size).min(encoded_samples.len());
            let batch_slice = &encoded_samples[start_idx..end_idx];
            if batch_slice.is_empty() {
                continue;
            }

            let batch_tensor = tokenizer.batch_to_tensor(batch_slice, &model.device)?;

            let loss = model.forward_loss(&batch_tensor)?;
            let loss_f32 = loss.to_scalar::<f32>()?;

            if step == 0 {
                initial_loss_val = loss_f32;
            }
            final_loss_val = loss_f32;

            // Compute autograd gradients & update LoRA Var tensors
            let grads = loss.backward()?;
            optimizer.step(&grads)?;
        }

        // Export trained LoRA adapters to standard HuggingFace SafeTensors format
        let adapter_map = model.export_adapter_tensors();
        let temp_path = std::env::temp_dir().join(format!(
            "adapter_{}_{}.safetensors",
            std::process::id(),
            rand::random::<u64>()
        ));
        save(&adapter_map, &temp_path)?;
        let safetensors_bytes = std::fs::read(&temp_path)?;
        let _ = std::fs::remove_file(&temp_path);

        // Compute adapter hash: SHA256(safetensors)
        let mut h = Sha256::new();
        h.update(&safetensors_bytes);
        let adapter_hash: [u8; 32] = h.finalize().into();

        // Generate secret salt
        let mut salt = [0u8; 32];
        rand::thread_rng().fill_bytes(&mut salt);

        // Commit hash: SHA256(adapter_hash || salt)
        let mut h_commit = Sha256::new();
        h_commit.update(&adapter_hash);
        h_commit.update(&salt);
        let commit_hash: [u8; 32] = h_commit.finalize().into();

        Ok(CandleTrainingArtifact {
            train_loss: initial_loss_val,
            final_loss: final_loss_val,
            safetensors_bytes,
            commit_hash,
            salt,
            adapter_hash,
            hardware_info: hyperparams.hardware_info.clone(),
        })
    }
}
