use crate::candle_peft::tokenizer::SimpleByteTokenizer;
use crate::candle_peft::transformer::CandleTransformerLM;
use anyhow::Result;
use candle_core::safetensors::save;
use candle_nn::{Optimizer, SGD};
use rand::RngCore;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// Training hyper-parameters for Candle Miner.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CandleMinerHyperparams {
    pub learning_rate: f64,
    pub steps: usize,
    pub batch_size: usize,
    pub hardware_info: String,
}

impl Default for CandleMinerHyperparams {
    fn default() -> Self {
        Self {
            learning_rate: 0.05,
            steps: 20,
            batch_size: 4,
            hardware_info: "NVIDIA CUDA / Candle Auto-Diff".to_string(),
        }
    }
}

/// Training artifact generated by a Candle miner node.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CandleTrainingArtifact {
    pub train_loss: f32,
    pub final_loss: f32,
    pub safetensors_bytes: Vec<u8>,
    pub commit_hash: [u8; 32],
    pub salt: [u8; 32],
    pub adapter_hash: [u8; 32],
    pub hardware_info: String,
}

/// Miner trainer executing real LoRA backpropagation and SafeTensors export on Candle models.
pub struct CandleMinerTrainer;

impl CandleMinerTrainer {
    /// Fine-tune LoRA parameters on a set of text training samples using Candle autograd.
    pub fn train(
        model: &mut CandleTransformerLM,
        text_samples: &[String],
        hyperparams: &CandleMinerHyperparams,
    ) -> Result<CandleTrainingArtifact> {
        let tokenizer = SimpleByteTokenizer::new();
        let encoded_samples: Vec<Vec<u32>> = text_samples
            .iter()
            .map(|text| tokenizer.encode(text))
            .filter(|v| v.len() >= 2)
            .collect();

        if encoded_samples.is_empty() {
            anyhow::bail!("No valid training samples provided");
        }

        let vars = model.get_trainable_vars();
        let mut optimizer = SGD::new(vars, hyperparams.learning_rate)?;

        let mut initial_loss_val = 0.0f32;
        let mut final_loss_val = 0.0f32;

        for step in 0..hyperparams.steps {
            // Select batch
            let start_idx = (step * hyperparams.batch_size) % encoded_samples.len();
            let end_idx = (start_idx + hyperparams.batch_size).min(encoded_samples.len());
            let batch_slice = &encoded_samples[start_idx..end_idx];
            if batch_slice.is_empty() {
                continue;
            }

            let batch_tensor = tokenizer.batch_to_tensor(batch_slice, &model.device)?;

            let loss = model.forward_loss(&batch_tensor)?;
            let loss_f32 = loss.to_scalar::<f32>()?;

            if step == 0 {
                initial_loss_val = loss_f32;
            }
            final_loss_val = loss_f32;

            // Compute autograd gradients & update LoRA Var tensors
            let grads = loss.backward()?;
            optimizer.step(&grads)?;
        }

        // Export trained LoRA adapters to standard HuggingFace SafeTensors format
        let adapter_map = model.export_adapter_tensors();
        let temp_path = std::env::temp_dir().join(format!("adapter_{}_{}.safetensors", std::process::id(), rand::random::<u64>()));
        save(&adapter_map, &temp_path)?;
        let safetensors_bytes = std::fs::read(&temp_path)?;
        let _ = std::fs::remove_file(&temp_path);

        // Compute adapter hash: SHA256(safetensors)
        let mut h = Sha256::new();
        h.update(&safetensors_bytes);
        let adapter_hash: [u8; 32] = h.finalize().into();

        // Generate secret salt
        let mut salt = [0u8; 32];
        rand::thread_rng().fill_bytes(&mut salt);

        // Commit hash: SHA256(adapter_hash || salt)
        let mut h_commit = Sha256::new();
        h_commit.update(&adapter_hash);
        h_commit.update(&salt);
        let commit_hash: [u8; 32] = h_commit.finalize().into();

        Ok(CandleTrainingArtifact {
            train_loss: initial_loss_val,
            final_loss: final_loss_val,
            safetensors_bytes,
            commit_hash,
            salt,
            adapter_hash,
            hardware_info: hyperparams.hardware_info.clone(),
        })
    }
}
