use crate::blockchain::types::TaskSpec;
use crate::ml::dataset::Dataset;
use crate::ml::model::{AdapterPackage, DePEFTModel};
use crate::storage::safetensors::serialize_safetensors;
use anyhow::Result;
use rand::Rng;
use sha2::{Digest, Sha256};

/// Miner training hyperparameter configuration.
#[derive(Debug, Clone)]
pub struct MinerHyperparams {
    pub learning_rate: f32,
    pub epochs: usize,
    pub batch_size: usize,
    pub hardware_type: String, // e.g. "NVIDIA RTX 4090 / CUDA", "AMD RX 7900 / ROCm"
}

impl Default for MinerHyperparams {
    fn default() -> Self {
        Self {
            learning_rate: 0.05,
            epochs: 5,
            batch_size: 16,
            hardware_type: "NVIDIA RTX 4090 / CUDA".to_string(),
        }
    }
}

/// Artifacts generated by a miner during QLoRA training.
#[derive(Debug, Clone)]
pub struct MinerTrainingArtifact {
    pub adapter_package: AdapterPackage,
    pub safetensors_bytes: Vec<u8>,
    pub adapter_hash: [u8; 32],
    pub salt: Vec<u8>,
    pub commit_hash: [u8; 32],
    pub train_loss: f64,
}

/// Miner QLoRA Training Engine.
pub struct MinerTrainer;

impl MinerTrainer {
    /// Perform QLoRA fine-tuning on base model using task training dataset.
    pub fn train(
        base_model: &DePEFTModel,
        dataset: &Dataset,
        task_spec: &TaskSpec,
        round: usize,
        hyperparams: &MinerHyperparams,
        rng: &mut impl Rng,
    ) -> Result<MinerTrainingArtifact> {
        let mut model = base_model.clone();
        let target_modules = task_spec.target_modules_str();

        // Train local QLoRA adapters across configured epochs
        for _ in 0..hyperparams.epochs {
            model.train_epoch(dataset, hyperparams.learning_rate, &target_modules);
        }

        let (train_loss, _) = model.evaluate(dataset, 0.0);
        let adapter_pkg = model.export_adapters(round);
        let safetensors_bytes = serialize_safetensors(&adapter_pkg)?;

        // Compute SHA-256 hash of adapter file
        let mut hasher = Sha256::new();
        hasher.update(&safetensors_bytes);
        let adapter_hash: [u8; 32] = hasher.finalize().into();

        // Generate 16-byte random salt to prevent pre-computation / front-running attacks
        let mut salt = vec![0u8; 16];
        rng.fill(&mut salt[..]);

        // Compute commit_hash = SHA256(adapter_hash || salt)
        let mut commit_hasher = Sha256::new();
        commit_hasher.update(&adapter_hash);
        commit_hasher.update(&salt);
        let commit_hash: [u8; 32] = commit_hasher.finalize().into();

        Ok(MinerTrainingArtifact {
            adapter_package: adapter_pkg,
            safetensors_bytes,
            adapter_hash,
            salt,
            commit_hash,
            train_loss,
        })
    }
}
